### PR TITLE
Fix UserTest

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
Expected error message changed. Stashing the `userId` for later use from `doSetup()` does not work.

#### Related Pull Requests
- https://github.com/LabKey/testAutomation/pull/2129

### CODE REVIEW

**Comment by labkey-adam** [comment]
@labkey-tchad @labkey-danield is there a good way to stash the `userId` at user creation time? Sticking it in a member var doesn't work... the infrastructure must toss the test instance after `doSetup()` is called.

**Comment by labkey-tchad** [comment]
> @labkey-tchad @labkey-danield is there a good way to stash the `userId` at user creation time? Sticking it in a member var doesn't work... the infrastructure must toss the test instance after `doSetup()` is called.

You could make `_normalUserId` static

**Comment by labkey-adam** [comment]
> > @labkey-tchad @labkey-danield is there a good way to stash the `userId` at user creation time? Sticking it in a member var doesn't work... the infrastructure must toss the test instance after `doSetup()` is called.
> 
> You could make `_normalUserId` static

Sure... as long as we never plan to run tests in parallel in the same VM

**Review by labkey-tchad — APPROVED** [review]

**Review by labkey-danield — APPROVED** [review]

**Comment by labkey-adam** [comment]
UserTest is all green: https://teamcity.labkey.org/buildConfiguration/LabKey_2411_Community_DailySuites_DailyCPostgres/3263589?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true

**Pull request merged**
