### PR TITLE
Automation test for View vs download options for file and attachment fields

### PR DESCRIPTION
**Pull request by labkey-sweta**
#### Rationale
Automation test for View vs download options for file and attachment fields

Added test case for attachment and file type fields in list and sample type respectively.

#### Related Pull Requests
* 

#### Changes
New test class
src/org/labkey/test/tests/AttachmentFieldTest.java

### CODE REVIEW

**Review by labkey-martyp — COMMENTED** [review]
This looks great Sweta. I probably wasn't very clear about assays and datasets. The field type for those is actually "File" and it will have the exact same behavior as "Attachment", but there is a different implementation on the server so it would be good to have a test for one of those types.

**Comment by labkey-sweta** [comment]
> Yes marty, thats why I have added one test case for sample type where the field is called File and one for lists where the field is Attachment.

You think adding for Assay or Dataset will add additional coverage?

**Comment by labkey-martyp** [comment]
> > Yes marty, thats why I have added one test case for sample type where the field is called File and one for lists where the field is Attachment.
> 
> You think adding for Assay or Dataset will add additional coverage?

Got it. The test name threw me off.  Looks good.

**Review by labkey-martyp — APPROVED** [review]

**Comment by labkey-sweta** [comment]
> > > Yes marty, thats why I have added one test case for sample type where the field is called File and one for lists where the field is Attachment.
> > 
> > 
> > You think adding for Assay or Dataset will add additional coverage?
> 
> Got it. The test name threw me off. Looks good.

Thought so..! i renamed it now. Thank you

**Pull request merged**
