### PR TITLE
fixTriggerScriptTest - remove toLower for casing for postgres and one deprecated method used in gwt lists -not needed now

### PR DESCRIPTION
**Pull request by labkey-ankurj**

### CODE REVIEW

**Review by labkey-tchad — APPROVED** [review]
Hooray for deleting code.

**Comment by cnathe** [comment]
@labkey-ankurj Looks like TeamCity is hitting a different failure in the TriggerScriptTest (but maybe getting further along):
https://teamcity.labkey.org/viewLog.html?buildId=968438&buildTypeId=LabkeyTrunk_DailyCPostgres&tab=buildResultsDiv&branch_LabkeyTrunk=fixCasingTriggerScriptTest

**Comment by labkey-ankurj** [comment]
The failing tests are passing locally for both postgres and mssql, I will kick TC again to see if they fail similarly again.

**Comment by labkey-ankurj** [comment]
@cnathe Tests passed this time https://teamcity.labkey.org/viewLog.html?buildId=975660&buildTypeId=LabkeyTrunk_DailyCPostgres

**Review by cnathe — APPROVED** [review]

**Pull request merged**
