### PR TITLE
Issue 40442: LinkedSchema should throw handled exception

### PR DESCRIPTION
**Pull request by labkey-kevink**
#### Rationale
Slightly better handling of a bad LinkedSchema configuration.  Instead of showing an error page, throw QueryParseException which is more gracefully handled in the schema browser and query-executeQuery.view action.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/1659

#### Changes
- update expected error

### CODE REVIEW

**Comment by labkey-kevink** [comment]
LinkedSchemaTest passed on TC: https://teamcity.labkey.org/viewLog.html?buildId=1156210&buildTypeId=bt20

**Review by labkey-tchad — APPROVED** [review]
I'm happy that `IntListDefinition` worked as well as it did! I don't think I ever actually tried it. I made some tweaks to clean it up a bit.
 - Made `ListDefinition` not handle any special `IntList` behavior.
 - Made it unnecessary to declare the key name twice for an `IntList`

**Comment by labkey-tchad** [comment]
Re-verified with my additional change: https://teamcity.labkey.org/buildConfiguration/bt20/1156412?buildTab=tests

**Review by labkey-kevink — COMMENTED** [review]
Thanks, that's much nicer.

**Pull request merged**
