### PR TITLE
Eliminate need for database properties in config.properties

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
These properties aren't needed. `databaseVersion` is rarely changed and fairly useless when it is changed. `databaseType` is unnecessary since it can be inferred from `jdbcDriverClassName`.

#### Changes
* Stop using these properties, except for remote server's use of `databaseType`

### CODE REVIEW

**Comment by labkey-adam** [comment]
@labkey-tchad I didn't test this locally... let me know if we should launch other test suites on this

**Comment by labkey-tchad** [comment]
Verifying against remote server: https://teamcity.labkey.org/buildConfiguration/LabKey_HostingAndEvaluationInfrastructure_AutomatedTest_AutomatedTestForTrunk_TrialBiologicsIntegrationTest/1896148
Might need to check the `databaseType` property as a fallback for this scenario

**Comment by labkey-tchad** [comment]
I updated this to check 'databaseType' as well as the driver name.
Reverifying remote server test:
https://teamcity.labkey.org/buildConfiguration/LabKey_HostingAndEvaluationInfrastructure_AutomatedTest_AutomatedTestForTrunk_TrialBiologicsIntegrationTest/1914866?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=false

**Comment by labkey-adam** [comment]
Thanks, @labkey-tchad! Code looks good to me. Assuming remote server test passes please approve and I'll merge.

I have a local change to get rid of these properties in the three template properties files... I'll get that committed after we merge this PR.

**Review by labkey-tchad — APPROVED** [review]
Remote server test started successfully (after that, any problems are unrelated to this change)

**Pull request merged**
