### PR TITLE
add dumbster page for app usage

### PR DESCRIPTION
**Pull request by labkey-chrisj**
#### Rationale
this adds a page class (and with it, a beginAt helper for that page) for the dumbster's begin view

#### Related Pull Requests
https://github.com/LabKey/biologics/pull/1050

#### Changes
just the new page class

### CODE REVIEW

**Review by labkey-tchad — CHANGES_REQUESTED** [review]
Not sure what additional functionality this proves over the existing `EmailRecordTable`. Maybe just add a `beginAt` method to `EmailRecordTable`. Also, containerPath is unnecessary; the email recorder is site-wide, not tied to a particular container.

**Comment by labkey-chrisj** [comment]
It adds the beginAt and the link to click back to the container, and the waitForPage (which might not be necessary)
only reason I added this as a page was for consistency; do we hang beginAts on components anywhere else?

I only plumbed the containerPath in there because you get that coming from goToModule from wherever you are; I also added the link back to the container b/c it's right there in the page

**Comment by labkey-tchad** [comment]
[`PipelineStatusTable`](https://github.com/LabKey/testAutomation/blob/develop/src/org/labkey/test/util/PipelineStatusTable.java#L58) has something similar to `beginAt`. Maybe a different method name would be good to let `beginAt` have a consistent meaning. Something like `goToDumbster`.

**Comment by labkey-chrisj** [comment]
That explains why we have a PipelineStatusDetailsPage but no PipelineStatusPage- we had a way to get to the pipelineStatusPage already.
I've been here for years and didn't know that until I spent some time trying to figure out why there wasn't a page for it
Usually when I write a new page class for an old component, it's because I had to spend time figuring out how to get the right component and didn't know the component by name off the top of my head, and I figured it would be worthwhile to save the next guy the effort/make the pieces more discoverable

**Pull request closed without merging**
