### PR TITLE
AssayExportImportTest fix by adding some time between assay run creation

### PR DESCRIPTION
**Pull request by cnathe**
#### Rationale
As mentioned in the TeamCity triage note for this failure, it looks like if "Save and Import Another Run" is used by the tests for multiple assay run creation, it can go so fast the the temp file names used for the assay data aren't unique and some runs are stomping on each other. This PR isn't perfect, but it adds a 1s sleep between assay run creation since it is unlikely that actual users could click this fast to create assay runs in sequence.

### CODE REVIEW

**Review by labkey-tchad — APPROVED** [review]
Comment should mention the file name collision.
Seems fine but are we sure we don't need a product fix. Could some sort of automated/bulk assay import script trigger this?

**Review by labkey-danield — APPROVED** [review]

**Comment by cnathe** [comment]
> Comment should mention the file name collision. Seems fine but are we sure we don't need a product fix. Could some sort of automated/bulk assay import script trigger this?

Good point, Trey. You mentioned something along those lines in the TC test failure note. I'll leave this PR open for a bit while I look into where and how the product is generating those file names to see if we can do something on that end to prevent the collision.

**Comment by cnathe** [comment]
Created a new PR with a platform change to add milliseconds to the assay run temp file name. If that PR gets approved / merged, I'll close out this one:
https://github.com/LabKey/platform/pull/3028

**Comment by cnathe** [comment]
Closing PR since https://github.com/LabKey/platform/pull/3028 fixes things on the product side.

**Pull request closed without merging**
