### PR TITLE
Update ImportDataPage to click correct submit button

### PR DESCRIPTION
**Pull request by labkey-tchad**
Fixes test failures: 
StudyContinuousTest.testSteps
StudyDateBasedTest
StudySimpleExportTest

### CODE REVIEW

**Comment by labkey-tchad** [comment]
Depends on changes in https://github.com/LabKey/platform/pull/254

**Comment by labkey-tchad** [comment]
Verifying on TeamCity:
https://teamcity.labkey.org/viewLog.html?buildId=780492
https://teamcity.labkey.org/viewLog.html?buildId=780494
https://teamcity.labkey.org/viewLog.html?buildId=780518

**Comment by labkey-jeckels** [comment]
I'll defer to someone on the test team for the code review here. But a reminder that we still need an approved issue.

**Comment by labkey-tchad** [comment]
Verifying study test failures:
https://teamcity.labkey.org/viewQueued.html?itemId=781658

**Comment by labkey-tchad** [comment]
https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=37987

**Pull request merged**
