### PR TITLE
Delete test files for long-deleted microarray assay functionality

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
We got rid of our MageML-based microarray assay years ago. It's time to let go of the associated test data files.

#### Changes
* Remove orphaned microarray test data

### CODE REVIEW

**Review by labkey-sweta — APPROVED** [review]
We can delete the folder Microarray too.

**Comment by labkey-jeckels** [comment]
@labkey-sweta the expressionMatrix subdirectory is still in use

**Review by labkey-tchad — CHANGES_REQUESTED** [review]
`NonStudyReportsTest`, `ReportAndDatasetNotificationTest`, and `ReportThumbnailTest` use these files. They don't need these files in particular, but will need to be updated to use some other image files.

**Comment by labkey-jeckels** [comment]
@labkey-tchad thanks for the pointer. We can leave these

**Pull request closed without merging**
