### PR TITLE
Update PipelineTriggerWizard to use new name for radio buttons.

### PR DESCRIPTION
**Pull request by labkey-danield**
#### Rationale
Update PipelineTriggerWizard to use new name for radio buttons.
Opened test issue [47109: Need to add test cases for "Update" option for PipelineTrigger](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=47109) to make track the automation gap for the update scenarios.

#### Related Pull Requests
* None

#### Changes
* Update PipelineTriggerWizard to use new name for radio buttons.

### CODE REVIEW

**Review by XingY — COMMENTED** [review]
The changes made are applicable for "Import Samples from data file" only. But for "Reload lists using data file", the old code applies. Will this test code change break lists reload?

**Comment by labkey-danield** [comment]
Good point @XingY. I only ran the specific tests that failed. I'll kick off more test runs and see what happens.
If this change does not break any other tests, which would imply there is an automation gap, I would be incline to check in the fix the get the existing tests to pass. Later when new tests are added PipelineTriggerWizard.java can be updated as needed.
If this change does break other tests then I will revisit and update my fix.

**Comment by labkey-danield** [comment]
@XingY , @labkey-tchad had a great suggestion on improving the finder for the radio buttons that I believe will work with the "Import Samples from data file" and "Reload lists using data file" scenarios. 
There is still a test automation gap but I think that is better addressed in a different change.

**Comment by XingY** [comment]
> @XingY , @labkey-tchad had a great suggestion on improving the finder for the radio buttons that I believe will work with the "Import Samples from data file" and "Reload lists using data file" scenarios. There is still a test automation gap but I think that is better addressed in a different change.

For the radio group id, samples is updated to use "insertOption" but list continue to use "mergeOption". I don't think the change works for list.

**Review by labkey-tchad — APPROVED** [review]
Looks good.
Is the `value` of the radio button not case-sensitive for that Locator? The failure snapshots had all-caps values (e.g. `value="MERGE"`)

**Comment by labkey-tchad** [comment]
> Looks good. Is the `value` of the radio button not case-sensitive for that Locator? The failure snapshots had all-caps values (e.g. `value="MERGE"`)

Oh, I see, you changed the callers to pass in all-caps.

**Pull request merged**
